builds:
  - env:
    - CGO_ENABLED=0
    binary: MqttCommander
    goos:
    - linux
    goarch:
    - amd64
    - arm64

dockers:
  - image_templates:
    - "calkoe/mqttcommander:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/amd64"
  - image_templates:
    - "calkoe/mqttcommander:{{ .Version }}-arm64v8"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/arm64/v8"

docker_manifests:
- name_template: "calkoe/mqttcommander:{{ .Version }}"
  image_templates:
  - "calkoe/mqttcommander:{{ .Version }}-amd64"
  - "calkoe/mqttcommander:{{ .Version }}-arm64v8"

nfpms:
  - maintainer: Calvin Köcher <calvin.koecher@alumni@fh-aachen.de>
    description: MQTT COMMANDER - A robust and easy to use MQTT rule engine
    homepage: https://github.com/calkoe/MqttCommander
    license: MIT
    formats:
    - deb