builds:
- env:
  - CGO_ENABLED=0
  binary: MqttCommander
  goos:
  - linux
  goarch:
  - amd64
  - arm64

dockers:
- image_templates:
  - "calkoe/mqttcommander:latest"
  - "calkoe/mqttcommander:{{ .Version }}"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "calkoe/mqttcommander:latest"
  - "calkoe/mqttcommander:{{ .Version }}"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"