# MQTT Automations 
# Constrains: [ Mqtt, Cron ]
# Actions:    [ Mqtt, Http ]

- Name: REGEX DEMO
  Constraints: 
    - Mqtt : demo/in1  == "v[0-9]"
    - Mqtt : demo/in2  == "v[0-9]" -NoTrigger 1
  Actions:
    - Mqtt : demo/put = "CRON AUSGELÖST"
    

