# MQTT Automations 
# Constrains: [ Mqtt, Cron ]
# Actions:    [ Mqtt, Http ]

- Name: Full Demo MQTT Automation
  Mode: AND
  Retrigger: true
  Pause: 10s
  Delay: 0s
  Reminder: 1m
  Constraints: 
    - Mqtt : demo/sensor|value <= "3" -Reset 2s  -Timeout 5s -BlockRetained 0
  Actions:
    - Mqtt : demo/actuator = 1 -Retained 0

- Name: Full Demo CRON Automation
  Delay: 10s
  Constraints: 
    - Cron : "* * * * * -Reset 30s"
  Actions:
    - Mqtt : pushover/calvin2 = "CRON AUSGELÖST"

- Name: Autobatterie Aileen Cron
  Mode: OR
  Pause: 2h
  Constraints: 
    - Mqtt : koecher/car1|voltage_v
    - Cron : "* 18-20 * * * -Reset 10s -NoTrigger 1"
  Actions:
    #- Mqtt : koecher/server/sms/calvin = "Aktuelle Spannung der Batterie ist {{ .Value }}V"
    #- Mqtt : koecher/server/sms/aileen = "Aktuelle Spannung der Batterie ist {{ .Value }}V"
