- Name: A - Check if Timeout is working
  Constraints: 
    - Mqtt : _test/3/con1.value <= 3 (Timeout 2s)
  Actions:
    - Mqtt : _test/3/a = 1 

- Name: B - Check if Pause and Delay is working
  Pause: 2s
  Delay: 2s
  Constraints: 
    - Mqtt : _test/3/a = 1
  Actions:
    - Mqtt : _test/3/b = 1 
    - Mqtt : _test/3/c = 0 

- Name: C - Check if Reminder is working
  Reminder: 1s
  Constraints: 
    - Mqtt : _test/3/b == 1
  Actions:
    - Mqtt : _test/3/c = 1

- Name: SUCCESS
  Constraints: 
    - Mqtt : _test/3/a = 1 
    - Mqtt : _test/3/b = 1 
    - Mqtt : _test/3/c = 1 
  Actions:
    - Mqtt : _test/3/success = 1 